# Exemple 1

In [366]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [368]:
# des données
data = {'ID':[1,2,3,4,5,6],
       'Onion':[1,0,0,1,1,1],
       'Potato':[1,1,0,1,1,1],
       'Burger':[1,1,0,0,1,1],
       'Milk':[0,1,1,1,0,1],
       'Beer':[0,0,1,0,1,0]}

In [370]:
# Création d'un DataFrame avec pandas à partir des données
df = pd.DataFrame(data, index=["Element 1", "Element 2","Element 3","Element 4","Element 5","Element 6"])

In [372]:

df = df[["ID", "Onion", "Potato", "Burger", "Milk", "Beer"]]
df

           ID  Onion  Potato  Burger  Milk  Beer
Element 1   1      1       1       1     0     0
Element 2   2      0       1       1     1     0
Element 3   3      0       0       0     1     1
Element 4   4      1       1       0     1     0
Element 5   5      1       1       1     0     1
Element 6   6      1       1       1     1     0

In [374]:
frequent_itemsets = apriori(df[['Onion', 'Potato', 'Burger', 'Milk', 'Beer' ]], min_support=0.50, use_colnames=True)

C:\Users\yacine.medjbeur\AppData\Local\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [376]:
frequent_itemsets

    support                 itemsets
0  0.666667                  (Onion)
1  0.833333                 (Potato)
2  0.666667                 (Burger)
3  0.666667                   (Milk)
4  0.666667          (Onion, Potato)
5  0.500000          (Burger, Onion)
6  0.666667         (Burger, Potato)
7  0.500000           (Potato, Milk)
8  0.500000  (Burger, Onion, Potato)

In [378]:
# Appliquer l'extraction des règles d'association à partir des itemsets fréquents
# Nous utilisons la métrique "lift" pour évaluer la qualité des règles. 
# Le lift mesure l'attractivité d'une règle, et nous définissons un seuil minimal de 1 pour le lift.
# `num_itemsets=1` n'est pas un paramètre valide pour association_rules. Cette ligne pourrait générer une erreur.
rules = association_rules(frequent_itemsets, 1, metric='lift', min_threshold=1.0)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Onion),(Potato),0.666667,0.833333,0.666667,1.00,1.200,1.0,0.111111,inf,0.500000,0.8,1.00,0.90
1,(Potato),(Onion),0.833333,0.666667,0.666667,0.80,1.200,1.0,0.111111,1.666667,1.000000,0.8,0.40,0.90
2,(Burger),(Onion),0.666667,0.666667,0.500000,0.75,1.125,1.0,0.055556,1.333333,0.333333,0.6,0.25,0.75
3,(Onion),(Burger),0.666667,0.666667,0.500000,0.75,1.125,1.0,0.055556,1.333333,0.333333,0.6,0.25,0.75
4,(Burger),(Potato),0.666667,0.833333,0.666667,1.00,1.200,1.0,0.111111,inf,0.500000,0.8,1.00,0.90
5,(Potato),(Burger),0.833333,0.666667,0.666667,0.80,1.200,1.0,0.111111,1.666667,1.000000,0.8,0.40,0.90
6,"(Burger, Onion)",(Potato),0.500000,0.833333,0.500000,1.00,1.200,1.0,0.083333,inf,0.333333,0.6,1.00,0.80
7,"(Burger, Potato)",(Onion),0.666667,0.666667,0.500000,0.75,1.125,1.0,0.055556,1.333333,0.333333,0.6,0.25,0.75
8,"(Onion, Potato)",(Burger),0.666667,0.666667,0.500000,0.75,1.125,1.0,0.055556,1.333333,0.333333,0.6,0.25,0.75
9,(Burger),"(Onion, Potato)",0.666667,0.666667,0.500000,0.75,1.125,1.0,0.055556,1.333333,0.333333,0.6,0.25,0.75
10,(Onion),"(Burger, Potato)",0.666667,0.666667,0.500000,0.75,1.125,1.0,0.055556,1.333333,0.333333,0.6,0.25,0.75
11,(Potato),"(Burger, Onion)",0.833333,0.500000,0.500000,0.60,1.200,1.0,0.083333,1.250000,1.000000,0.6,0.20,0.80

In [380]:
# Filtrer les règles d'association selon deux critères :
# 1. Le lift doit être supérieur à 1.125 (indiquant que la règle est plus intéressante que ce à quoi on s'attendait par hasard)
# 2. La confiance (probabilité de l'achat du conséquent) doit être supérieure à 0.8 (indiquant que la règle est forte)
rules [ (rules['lift'] >1.125)  & (rules['confidence']> 0.8)  ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Onion),(Potato),0.666667,0.833333,0.666667,1.0,1.2,1.0,0.111111,inf,0.500000,0.8,1.0,0.9
4,(Burger),(Potato),0.666667,0.833333,0.666667,1.0,1.2,1.0,0.111111,inf,0.500000,0.8,1.0,0.9
6,"(Burger, Onion)",(Potato),0.500000,0.833333,0.500000,1.0,1.2,1.0,0.083333,inf,0.333333,0.6,1.0,0.8

# Exemple 2

In [383]:
# exemple des données
retail_shopping_basket = {'ID':[1,2,3,4,5,6],
                         'Basket':[['Beer', 'Diaper', 'Pretzels', 'Chips', 'Aspirin'],
                                   ['Diaper', 'Beer', 'Chips', 'Lotion', 'Juice', 'BabyFood', 'Milk'],
                                   ['Soda', 'Chips', 'Milk'],
                                   ['Soup', 'Beer', 'Diaper', 'Milk', 'IceCream'],
                                   ['Soda', 'Coffee', 'Milk', 'Bread'],
                                   ['Beer', 'Chips']
                                  ]
                         }

In [385]:
# Création d'un DataFrame avec pandas à partir des données
retail = pd.DataFrame(retail_shopping_basket, index=["Element 1", "Element 2","Element 3","Element 4","Element 5","Element 6"])

In [387]:
retail = retail[['ID', 'Basket']]
retail # afficher la colonne ID et Basket

           ID                                             Basket
Element 1   1           [Beer, Diaper, Pretzels, Chips, Aspirin]
Element 2   2  [Diaper, Beer, Chips, Lotion, Juice, BabyFood,...
Element 3   3                                [Soda, Chips, Milk]
Element 4   4               [Soup, Beer, Diaper, Milk, IceCream]
Element 5   5                        [Soda, Coffee, Milk, Bread]
Element 6   6                                      [Beer, Chips]

In [389]:
from sklearn.preprocessing import MultiLabelBinarizer # Importer la classe MultiLabelBinarizer de la bibliothèque scikit-learn.
mlb = MultiLabelBinarizer() # Initialisation d'une instance de la classe MultiLabelBinarizer.
# Appliquer la transformation et convertir les étiquettes multi-catégories en format binaire. # Spécifier les noms des colonnes basés sur les classes identifiées par MultiLabelBinarizer.
pd.DataFrame(mlb.fit_transform(retail.Basket), columns=mlb.classes_ , index=["Element 1", "Element 2","Element 3","Element 4","Element 5","Element 6"])
# index= :  Définir les noms des lignes.

,Aspirin,BabyFood,Beer,Bread,Chips,Coffee,Diaper,IceCream,Juice,Lotion,Milk,Pretzels,Soda,Soup
Element 1,1,0,1,0,1,0,1,0,0,0,0,1,0,0
Element 2,0,1,1,0,1,0,1,0,1,1,1,0,0,0
Element 3,0,0,0,0,1,0,0,0,0,0,1,0,1,0
Element 4,0,0,1,0,0,0,1,1,0,0,1,0,0,1
Element 5,0,0,0,1,0,1,0,0,0,0,1,0,1,0
Element 6,0,0,1,0,1,0,0,0,0,0,0,0,0,0

In [391]:
retail = retail.drop('Basket' ,axis=1).join(retail.Basket.str.join(',').str.get_dummies(','))
# retail.drop('Basket' ,axis=1) : pour supprimer la colonne basket
# join(retail.Basket.str.join(',') : Convertir chaque liste dans 'Basket' en une chaîne de caractères, où les éléments sont séparés par des virgules.
# str.get_dummies(',') :  Créer des colonnes binaires pour chaque élément unique, en utilisant la virgule comme séparateur.
retail

,ID,Aspirin,BabyFood,Beer,Bread,Chips,Coffee,Diaper,IceCream,Juice,Lotion,Milk,Pretzels,Soda,Soup
Element 1,1,1,0,1,0,1,0,1,0,0,0,0,1,0,0
Element 2,2,0,1,1,0,1,0,1,0,1,1,1,0,0,0
Element 3,3,0,0,0,0,1,0,0,0,0,0,1,0,1,0
Element 4,4,0,0,1,0,0,0,1,1,0,0,1,0,0,1
Element 5,5,0,0,0,1,0,1,0,0,0,0,1,0,1,0
Element 6,6,0,0,1,0,1,0,0,0,0,0,0,0,0,0

In [393]:
frequent_itemsets_2 = apriori(retail.drop('ID',axis=1), use_colnames=True)
frequent_itemsets_2

C:\Users\yacine.medjbeur\AppData\Local\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

    support        itemsets
0  0.666667          (Beer)
1  0.666667         (Chips)
2  0.500000        (Diaper)
3  0.666667          (Milk)
4  0.500000   (Beer, Chips)
5  0.500000  (Beer, Diaper)

In [395]:
association_rules(frequent_itemsets_2, metric='lift',num_itemsets= 1)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Beer),(Chips),0.666667,0.666667,0.5,0.75,1.125,1.0,0.055556,1.333333,0.333333,0.60,0.25,0.750
1,(Chips),(Beer),0.666667,0.666667,0.5,0.75,1.125,1.0,0.055556,1.333333,0.333333,0.60,0.25,0.750
2,(Beer),(Diaper),0.666667,0.500000,0.5,0.75,1.500,1.0,0.166667,2.000000,1.000000,0.75,0.50,0.875
3,(Diaper),(Beer),0.500000,0.666667,0.5,1.00,1.500,1.0,0.166667,inf,0.666667,0.75,1.00,0.875

In [397]:
association_rules(frequent_itemsets_2, num_itemsets=1)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Diaper),(Beer),0.5,0.666667,0.5,1.0,1.5,1.0,0.166667,inf,0.666667,0.75,1.0,0.875

# Exemple 3

In [400]:
movies = pd.read_csv(r'C:\Users\yacine.medjbeur\Documents\ml-latest-small\ml-latest-small\movies.csv') # recupérer les données

In [402]:
movies.head(10) # afficher les 10 premier movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller

In [404]:
movies_ohe = movies.join(movies.genres.str.get_dummies())
movies_ohe

,movieId,title,genres,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),Adventure|Children|Fantasy,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),Comedy|Romance,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0
4,5,Father of the Bride Part II (1995),Comedy,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,0,1,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
9739,193585,Flint (2017),Drama,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [406]:
pd.options.display.max_columns=100

In [408]:
movies_ohe.head()

,movieId,title,genres,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),Adventure|Children|Fantasy,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),Comedy|Romance,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0
4,5,Father of the Bride Part II (1995),Comedy,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [410]:
stat1 = movies_ohe.drop(['title', 'movieId'],axis=1).apply(pd.value_counts)

C:\Users\yacine.medjbeur\AppData\Local\Temp\ipykernel_7564\1177173523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  stat1 = movies_ohe.drop(['title', 'movieId'],axis=1).apply(pd.value_counts)
C:\Users\yacine.medjbeur\AppData\Local\Temp\ipykernel_7564\1177173523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  stat1 = movies_ohe.drop(['title', 'movieId'],axis=1).apply(pd.value_counts)

TypeError: '<' not supported between instances of 'int' and 'str'

In [412]:
stat1 = stat1.transpose().drop(0,axis=1).sort_values(by=1, ascending=False).rename(columns={1:'No. of movies'})

KeyError: '[0] not found in axis'

In [414]:
stat2 = movies.join(movies.genres.str.split('|').reset_index().genres.str.len(), rsuffix='r').rename(columns={'genresr':'genre_count'}).drop(["title",	"movieId"],axis=1)

In [416]:
stat2 = stat2[stat2['genre_count']==1].drop([],axis=1).groupby('genres').sum().sort_values(by='genre_count', ascending=False)

In [418]:
stat = stat1.merge(stat2, how='left', left_index=True, right_index=True).fillna(0)

In [420]:
stat.genre_count=stat.genre_count.astype(int)
stat.rename(columns={'genre_count': 'No. of movies with only 1 genre'},inplace=True)

In [422]:
stat

                    No. of movies  No. of movies with only 1 genre
Drama                        4361                             1053
Comedy                       3756                              946
Thriller                     1894                               84
Action                       1828                               60
Romance                      1596                               21
Adventure                    1263                               12
Crime                        1199                               12
Sci-Fi                        980                               37
Horror                        978                              167
Fantasy                       779                                4
Children                      664                                4
Animation                     611                               30
Mystery                       573                                3
Documentary                   440                              339
War                           382                                4
Musical                       334                               15
Western                       167                               23
IMAX                          158                                0
Film-Noir                      87                                3
(no genres listed)             34                               34

In [449]:
import matplotlib.pyplot as plt
%matplotlib inline
movies_ohe.set_index(['movieId','title']).sum(axis=1).hist()
plt.title('distribution of number of genres')

C:\Users\yacine.medjbeur\AppData\Roaming\Python\Python312\site-packages\IPython\core\pylabtools.py:77: DeprecationWarning: backends is deprecated since IPython 8.24, backends are managed in matplotlib and can be externally registered.
  warnings.warn(

KeyError: "None of ['movieId', 'title'] are in the columns"

# Let's get back to analysing the genre associations:

In [445]:
movies_ohe.set_index(["movieId","title"], inplace=True)

In [447]:
frequent_itemsets_movies = apriori(movies_ohe,use_colnames=True, min_support=0.025)

C:\Users\yacine.medjbeur\AppData\Local\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

ValueError: The allowed values for a DataFrame are True, False, 0, 1. Found value Adventure|Animation|Children|Comedy|Fantasy

In [431]:
frequent_itemsets_movies

     support                  itemsets
0   0.187641                  (Action)
1   0.129645               (Adventure)
2   0.062718               (Animation)
3   0.068158                (Children)
4   0.385547                  (Comedy)
5   0.123075                   (Crime)
6   0.045165             (Documentary)
7   0.447649                   (Drama)
8   0.079963                 (Fantasy)
9   0.100390                  (Horror)
10  0.034285                 (Musical)
11  0.058817                 (Mystery)
12  0.163827                 (Romance)
13  0.100595                  (Sci-Fi)
14  0.194416                (Thriller)
15  0.039212                     (War)
16  0.062615       (Adventure, Action)
17  0.044036          (Action, Comedy)
18  0.042907           (Action, Crime)
19  0.054301           (Action, Drama)
20  0.046294          (Action, Sci-Fi)
21  0.067235        (Action, Thriller)
22  0.025354    (Adventure, Animation)
23  0.032026     (Adventure, Children)
24  0.040957       (Adventure, Comedy)
25  0.031924        (Adventure, Drama)
26  0.034285      (Adventure, Fantasy)
27  0.031410       (Adventure, Sci-Fi)
28  0.031000     (Children, Animation)
29  0.027612       (Comedy, Animation)
30  0.037159        (Children, Comedy)
31  0.035414           (Crime, Comedy)
32  0.103983           (Drama, Comedy)
33  0.030076         (Comedy, Fantasy)
34  0.090741         (Romance, Comedy)
35  0.065387            (Crime, Drama)
36  0.058407         (Thriller, Crime)
37  0.029563          (Drama, Mystery)
38  0.095874          (Romance, Drama)
39  0.085403         (Thriller, Drama)
40  0.030589              (War, Drama)
41  0.047116        (Thriller, Horror)
42  0.036338       (Thriller, Mystery)
43  0.031000        (Thriller, Sci-Fi)
44  0.035106  (Romance, Drama, Comedy)
45  0.031718  (Thriller, Drama, Crime)

In [433]:
rules_movies =  association_rules(frequent_itemsets_movies, metric='lift', min_threshold=1.25, num_itemsets=1)

In [435]:
rules_movies

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Adventure),(Action),0.129645,0.187641,0.062615,0.482977,2.573940,1.0,0.038289,1.571224,0.702576,0.245869,0.363553,0.408338
1,(Action),(Adventure),0.187641,0.129645,0.062615,0.333698,2.573940,1.0,0.038289,1.306247,0.752735,0.245869,0.234448,0.408338
2,(Action),(Crime),0.187641,0.123075,0.042907,0.228665,1.857929,1.0,0.019813,1.136892,0.568426,0.160215,0.120409,0.288645
3,(Crime),(Action),0.123075,0.187641,0.042907,0.348624,1.857929,1.0,0.019813,1.247142,0.526575,0.160215,0.198167,0.288645
4,(Action),(Sci-Fi),0.187641,0.100595,0.046294,0.246718,2.452576,1.0,0.027419,1.193981,0.729069,0.191345,0.162466,0.353461
5,(Sci-Fi),(Action),0.100595,0.187641,0.046294,0.460204,2.452576,1.0,0.027419,1.504937,0.658508,0.191345,0.335520,0.353461
6,(Action),(Thriller),0.187641,0.194416,0.067235,0.358315,1.843034,1.0,0.030754,1.255420,0.563072,0.213564,0.203454,0.352072
7,(Thriller),(Action),0.194416,0.187641,0.067235,0.345829,1.843034,1.0,0.030754,1.241814,0.567807,0.213564,0.194726,0.352072
8,(Adventure),(Animation),0.129645,0.062718,0.025354,0.195566,3.118175,1.0,0.017223,1.165145,0.780486,0.151813,0.141737,0.299911
9,(Animation),(Adventure),0.062718,0.129645,0.025354,0.404255,3.118175,1.0,0.017223,1.460953,0.724755,0.151813,0.315515,0.299911
10,(Adventure),(Children),0.129645,0.068158,0.032026,0.247031,3.624360,1.0,0.023190,1.237556,0.831947,0.193189,0.191956,0.358455
11,(Children),(Adventure),0.068158,0.129645,0.032026,0.469880,3.624360,1.0,0.023190,1.641806,0.777052,0.193189,0.390915,0.358455
12,(Adventure),(Fantasy),0.129645,0.079963,0.034285,0.264450,3.307149,1.0,0.023918,1.250815,0.801540,0.195550,0.200521,0.346602
13,(Fantasy),(Adventure),0.079963,0.129645,0.034285,0.428755,3.307149,1.0,0.023918,1.523610,0.758257,0.195550,0.343664,0.346602
14,(Adventure),(Sci-Fi),0.129645,0.100595,0.031410,0.242280,2.408464,1.0,0.018369,1.186989,0.671907,0.157976,0.157532,0.277263
15,(Sci-Fi),(Adventure),0.100595,0.129645,0.031410,0.312245,2.408464,1.0,0.018369,1.265502,0.650205,0.157976,0.209799,0.277263
16,(Children),(Animation),0.068158,0.062718,0.031000,0.454819,7.251799,1.0,0.026725,1.719213,0.925161,0.310380,0.418339,0.474545
17,(Animation),(Children),0.062718,0.068158,0.031000,0.494272,7.251799,1.0,0.026725,1.842573,0.919791,0.310380,0.457281,0.474545
18,(Children),(Comedy),0.068158,0.385547,0.037159,0.545181,1.414044,1.0,0.010880,1.350983,0.314226,0.089207,0.259798,0.320780
19,(Comedy),(Children),0.385547,0.068158,0.037159,0.096379,1.414044,1.0,0.010880,1.031231,0.476535,0.089207,0.030285,0.320780
20,(Romance),(Comedy),0.163827,0.385547,0.090741,0.553885,1.436620,1.0,0.027578,1.377341,0.363467,0.197851,0.273963,0.394621
21,(Comedy),(Romance),0.385547,0.163827,0.090741,0.235357,1.436620,1.0,0.027578,1.093547,0.494622,0.197851,0.085545,0.394621
22,(Thriller),(Crime),0.194416,0.123075,0.058407,0.300422,2.440963,1.0,0.034479,1.253506,0.732792,0.225436,0.202237,0.387492
23,(Crime),(Thriller),0.123075,0.194416,0.058407,0.474562,2.440963,1.0,0.034479,1.533167,0.673177,0.225436,0.347755,0.387492
24,(Romance),(Drama),0.163827,0.447649,0.095874,0.585213,1.307302,1.0,0.022537,1.331649,0.281121,0.185945,0.249051,0.399692
25,(Drama),(Romance),0.447649,0.163827,0.095874,0.214171,1.307302,1.0,0.022537,1.064065,0.425574,0.185945,0.060208,0.399692
26,(War),(Drama),0.039212,0.447649,0.030589,0.780105,1.742669,1.0,0.013036,2.511880,0.443560,0.067042,0.601892,0.424219
27,(Drama),(War),0.447649,0.039212,0.030589,0.068333,1.742669,1.0,0.013036,1.031257,0.771553,0.067042,0.030310,0.424219
28,(Thriller),(Horror),0.194416,0.100390,0.047116,0.242344,2.414026,1.0,0.027598,1.187360,0.727118,0.190220,0.157795,0.355835
29,(Horror),(Thriller),0.100390,0.194416,0.047116,0.469325,2.414026,1.0,0.027598,1.518037,0.651120,0.190220,0.341255,0.355835
30,(Thriller),(Mystery),0.194416,0.058817,0.036338,0.186906,3.177729,1.0,0.024902,1.157532,0.850699,0.167534,0.136093,0.402354
31,(Mystery),(Thriller),0.058817,0.194416,0.036338,0.617801,3.177729,1.0,0.024902,2.107761,0.728137,0.167534,0.525563,0.402354
32,(Thriller),(Sci-Fi),0.194416,0.100595,0.031000,0.159451,1.585072,1.0,0.011442,1.070020,0.458194,0.117418,0.065438,0.233807
33,(Sci-Fi),(Thriller),0.100595,0.194416,0.031000,0.308163,1.585072,1.0,0.011442,1.164414,0.410398,0.117418,0.141199,0.233807
34,"(Drama, Comedy)",(Romance),0.103983,0.163827,0.035106,0.337611,2.060781,1.0,0.018071,1.262360,0.574484,0.150860,0.207833,0.275948
35,(Romance),"(Drama, Comedy)",0.163827,0.103983,0.035106,0.214286,2.060781,1.0,0.018071,1.140386,0.615599,0.150860,0.123104,0.275948
36,"(Thriller, Drama)",(Crime),0.085403,0.123075,0.031718,0.371394,3.017617,1.0,0.021207,1.395031,0.731047,0.179443,0.283170,0.314554
37,"(Crime, Drama)",(Thriller),0.065387,0.194416,0.031718,0.485086,2.495096,1.0,0.019006,1.564503,0.641136,0.139064,0.360819,0.324117
38,(Thriller),"(Crime, Drama)",0.194416,0.065387,0.031718,0.163147,2.495096,1.0,0.019006,1.116818,0.743825,0.139064,0.104599,0.324117
39,(Crime),"(Thriller, Drama)",0.123075,0.085403,0.031718,0.257715,3.017617,1.0,0.021207,1.232136,0.762452,0.179443,0.188401,0.314554

In [437]:
rules_movies[(rules_movies.conviction>1.25)] # mettre un condition que le soit le confiction > 1.25

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Adventure),(Action),0.129645,0.187641,0.062615,0.482977,2.573940,1.0,0.038289,1.571224,0.702576,0.245869,0.363553,0.408338
1,(Action),(Adventure),0.187641,0.129645,0.062615,0.333698,2.573940,1.0,0.038289,1.306247,0.752735,0.245869,0.234448,0.408338
5,(Sci-Fi),(Action),0.100595,0.187641,0.046294,0.460204,2.452576,1.0,0.027419,1.504937,0.658508,0.191345,0.335520,0.353461
6,(Action),(Thriller),0.187641,0.194416,0.067235,0.358315,1.843034,1.0,0.030754,1.255420,0.563072,0.213564,0.203454,0.352072
9,(Animation),(Adventure),0.062718,0.129645,0.025354,0.404255,3.118175,1.0,0.017223,1.460953,0.724755,0.151813,0.315515,0.299911
11,(Children),(Adventure),0.068158,0.129645,0.032026,0.469880,3.624360,1.0,0.023190,1.641806,0.777052,0.193189,0.390915,0.358455
12,(Adventure),(Fantasy),0.129645,0.079963,0.034285,0.264450,3.307149,1.0,0.023918,1.250815,0.801540,0.195550,0.200521,0.346602
13,(Fantasy),(Adventure),0.079963,0.129645,0.034285,0.428755,3.307149,1.0,0.023918,1.523610,0.758257,0.195550,0.343664,0.346602
15,(Sci-Fi),(Adventure),0.100595,0.129645,0.031410,0.312245,2.408464,1.0,0.018369,1.265502,0.650205,0.157976,0.209799,0.277263
16,(Children),(Animation),0.068158,0.062718,0.031000,0.454819,7.251799,1.0,0.026725,1.719213,0.925161,0.310380,0.418339,0.474545
17,(Animation),(Children),0.062718,0.068158,0.031000,0.494272,7.251799,1.0,0.026725,1.842573,0.919791,0.310380,0.457281,0.474545
18,(Children),(Comedy),0.068158,0.385547,0.037159,0.545181,1.414044,1.0,0.010880,1.350983,0.314226,0.089207,0.259798,0.320780
20,(Romance),(Comedy),0.163827,0.385547,0.090741,0.553885,1.436620,1.0,0.027578,1.377341,0.363467,0.197851,0.273963,0.394621
22,(Thriller),(Crime),0.194416,0.123075,0.058407,0.300422,2.440963,1.0,0.034479,1.253506,0.732792,0.225436,0.202237,0.387492
23,(Crime),(Thriller),0.123075,0.194416,0.058407,0.474562,2.440963,1.0,0.034479,1.533167,0.673177,0.225436,0.347755,0.387492
24,(Romance),(Drama),0.163827,0.447649,0.095874,0.585213,1.307302,1.0,0.022537,1.331649,0.281121,0.185945,0.249051,0.399692
26,(War),(Drama),0.039212,0.447649,0.030589,0.780105,1.742669,1.0,0.013036,2.511880,0.443560,0.067042,0.601892,0.424219
29,(Horror),(Thriller),0.100390,0.194416,0.047116,0.469325,2.414026,1.0,0.027598,1.518037,0.651120,0.190220,0.341255,0.355835
31,(Mystery),(Thriller),0.058817,0.194416,0.036338,0.617801,3.177729,1.0,0.024902,2.107761,0.728137,0.167534,0.525563,0.402354
34,"(Drama, Comedy)",(Romance),0.103983,0.163827,0.035106,0.337611,2.060781,1.0,0.018071,1.262360,0.574484,0.150860,0.207833,0.275948
36,"(Thriller, Drama)",(Crime),0.085403,0.123075,0.031718,0.371394,3.017617,1.0,0.021207,1.395031,0.731047,0.179443,0.283170,0.314554
37,"(Crime, Drama)",(Thriller),0.065387,0.194416,0.031718,0.485086,2.495096,1.0,0.019006,1.564503,0.641136,0.139064,0.360819,0.324117

In [439]:
rules_movies[(rules_movies.conviction>1.5)].sort_values(by=['lift','conviction'], ascending=False) 
# mettre un condition que le soit le confiction > 1.25
# sort_values(by=['lift','conviction'], ascending=False :  ordre de plus bas jusqu'a plus haut

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
17,(Animation),(Children),0.062718,0.068158,0.031000,0.494272,7.251799,1.0,0.026725,1.842573,0.919791,0.310380,0.457281,0.474545
16,(Children),(Animation),0.068158,0.062718,0.031000,0.454819,7.251799,1.0,0.026725,1.719213,0.925161,0.310380,0.418339,0.474545
11,(Children),(Adventure),0.068158,0.129645,0.032026,0.469880,3.624360,1.0,0.023190,1.641806,0.777052,0.193189,0.390915,0.358455
13,(Fantasy),(Adventure),0.079963,0.129645,0.034285,0.428755,3.307149,1.0,0.023918,1.523610,0.758257,0.195550,0.343664,0.346602
31,(Mystery),(Thriller),0.058817,0.194416,0.036338,0.617801,3.177729,1.0,0.024902,2.107761,0.728137,0.167534,0.525563,0.402354
0,(Adventure),(Action),0.129645,0.187641,0.062615,0.482977,2.573940,1.0,0.038289,1.571224,0.702576,0.245869,0.363553,0.408338
37,"(Crime, Drama)",(Thriller),0.065387,0.194416,0.031718,0.485086,2.495096,1.0,0.019006,1.564503,0.641136,0.139064,0.360819,0.324117
5,(Sci-Fi),(Action),0.100595,0.187641,0.046294,0.460204,2.452576,1.0,0.027419,1.504937,0.658508,0.191345,0.335520,0.353461
23,(Crime),(Thriller),0.123075,0.194416,0.058407,0.474562,2.440963,1.0,0.034479,1.533167,0.673177,0.225436,0.347755,0.387492
29,(Horror),(Thriller),0.100390,0.194416,0.047116,0.469325,2.414026,1.0,0.027598,1.518037,0.651120,0.190220,0.341255,0.355835
26,(War),(Drama),0.039212,0.447649,0.030589,0.780105,1.742669,1.0,0.013036,2.511880,0.443560,0.067042,0.601892,0.424219

In [441]:
pd.options.display.max_rows=50

In [443]:
movies[(movies.genres.str.contains('Adventure')) & (movies.genres.str.contains('Children')) & (~movies.genres.str.contains('Animation'))]

,movieId,title,genres
1,2,Jumanji (1995),Adventure|Children|Fantasy
7,8,Tom and Huck (1995),Adventure|Children
53,60,"Indian in the Cupboard, The (1995)",Adventure|Children|Fantasy
95,107,Muppet Treasure Island (1996),Adventure|Children|Comedy|Musical
109,126,"NeverEnding Story III, The (1994)",Adventure|Children|Fantasy
...,...,...,...
9428,166203,Sapphire Blue (2014),Adventure|Children|Fantasy|Sci-Fi
9565,173873,Gulliver's Travels (1996),Adventure|Children|Fantasy
9636,179401,Jumanji: Welcome to the Jungle (2017),Action|Adventure|Children
9697,184987,A Wrinkle in Time (2018),Adventure|Children|Fantasy|Sci-Fi
9710,187595,Solo: A Star Wars Story (2018),Action|Adventure|Children|Sci-Fi